# Generated by Django 4.1.3 on 2024-08-02 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fires', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.CharField(max_length=50, unique=True)),
                ('user', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
