# Generated by Django 4.1.3 on 2024-08-11 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fires', '0002_twitterreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wildfire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('summary', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WildfireDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_text', models.TextField()),
                ('wildfire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='fires.wildfire')),
            ],
        ),
        migrations.DeleteModel(
            name='FireReport',
        ),
        migrations.DeleteModel(
            name='TwitterReport',
        ),
    ]
